import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header/Header";
import { CartProvider } from "@/context/CartContext";
import { getCart } from "./api/cart/cart";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cart = await getCart();

  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider cart={cart}>
          <Header />
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
